name: deploy

on:
  push:
    branches: [main]
  pull_request:

jobs:

  build-and-deploy:
    runs-on: cfa-cdcgov
    environment: production
    steps:
    - name: Azure Service Principal CLI login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Configure Docker
      uses: docker/setup-buildx-action@v3

    - name: Azure ACR login
      uses: docker/login-action@v3
      with:
        login-server: cfaprdbatchcr.azurecr.io
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: cfaprdbatchcr.azurecr.io/rt-postprocessing:latest
